export const { berengersLines, jeansLines };

const berengersLines = [
    "I get so little spare time!",
    "It's too late now.",
    "How do you mean?",
    "You're right!",
    "Unfortunately, no. I've only heard people talk about them.",
    "It would be an excellent initiation into the artistic life of our times.",
    "You're right, perfectly right. I'm going to put myself into the picture, like you said.",
    "I will, I promise you.",
    "I make myself a solemn promise, I'll keep my word to myself.",
    "Instead of drinking, I'll develop my mind. I feel better already. My head already feels clearer.",
    "This afternoon I'll go to the museum. And I’ll book two seats for the theatre this evening. Will you come with me?",
    "I promise you, and I promise myself. Will you come to the museum with me this afternoon?",
    "But you will come with me to the theatre this evening?",
    "For a drink?",
    "Ah, now it's you that's setting me a bad example! You're going out drinking.",
    "Why isn't it the same thing?",
    "I didn't mean you were a drunkard. But why would it make me one any more than you, in a case like that?",
    "What about me, what? What did you say?",
    "Rhinoceros! In the opposite direction!",
    "Oh, Daisy!",
    "I've barely got the strength to go on living. Maybe I don't even want to.",
    "Solitude seems to oppress me. And so does the company of other people.",
    "Life is an abnormal business.",
    "There are more dead people than living. And their numbers are increasing. The living are getting rarer.",
    ": I sometimes wonder if I exist myself JEAN: You don't exist, my dear Berenger, because you don't think. Start thinking, then you will.",
    "Who?",
    "In any case, I think she's already got her eye on someone.",
    "Dudard. An office colleague, qualified in law, with a big future in the firm - and in Daisy's affections. I can't hope to compete with him.",
    "The Chief thinks a lot of him. Whereas I've no future, I’ve no qualifications. I don't stand a chance.",
    "What else can I do?",
    "Where can I find the weapons?",
    "What weapons?",
    "How do I get myself up to the mark?",
    "That's not so easy.",
    "It may be simple for you, but not for me.",
    "I really don't see how.",
    "The laundry's so expensive.",
    "Then what do I do? Tell me.",
    "I'm listening.",
    "I've got talent, me?"
]

const jeansLines = [
    "You contradict yourself What oppresses you - solitude, or the company of others? You consider yourself a thinker, yet you're devoid of logic.",
    "On the contrary. Nothing could be more natural, and the proof is that people go On living.",
    "The dead don't exist, there's no getting away from that! Ah! Ah ...! [He gives a huge laugh.] Yet you're oppressed by them, too? How can you be oppressed by something that doesn't exist?",
    "Fundamentally you're just a bluffer. And a liar. You say that life doesn't interest you. And yet there's somebody who does.",
    "Your little friend from the office who just went past. You're very fond of her!",
    "You didn't want her to see you in your present state. [BERENGER makes a gesture.] That proves you're not indifferent to everything. But how can you expect Daisy to be attracted to a drunkard?",
    "Oh, who?",
    "So you're giving up, just like that...?",
    "Life is a struggle, it's cowardly not to put up a fight!",
    "Then find yourself some weapons, my friend.",
    "Within yourself Through your own will.",
    "The weapons of patience and culture, the weapons of the mind. [BERENGER yawns.] Turn yourself into a keen and brilliant intellect. Get yourself up to the mark!",
    "Come on, exercise your will. Concentrate I.",
    "You have to be told everything.",
    "This is what you must do: dress yourself properly, shave every day, put on a clean shirt.",
    "Cut down on your drinking. This is the way to come out: wear a hat, a tie like this, a well-cut suit, shoes well polished. [As he mentions the various items of clothing he points self-contentedly to his own hat, tie, and shoes.]",
    "You're a timid creature, but not without talent",
    "So use it. Put yourself in the picture. Keep abreast of the cultural and literary events of the times.",
    "Take advantage of what free time you do have. Don't just let yourself drift.",
    "One can always find time.",
    "It's never too late.",
    "You work eight hours a day, like me and everybody else, but not on Sundays, nor in the evening, nor for three weeks in the summer. That's quite sufficient, with a little method",
    "Look, instead of drinking and feeling sick, isn't it better to be fresh and eager, even at work? And you can spend your free time constructively.",
    "By visiting museums, reading literary periodicals, going to lectures. That'll solve your troubles, it will develop your mind. In four weeks you'll be a cultured man.",
    "You see, you even think so yourself!",
    "Instead of squandering all your spare money on drink, isn't it better to buy a ticket for an interesting play? Do you know anything about the avant-garde theatre there's so much talk about? Have you seen Ionesco's plays?",
    "There's one playing now. Take advantage of it.",
    "You promise yourself, that's the main thing.",
    "You see!",
    "You must persevere. Keep up your good resolutions.",
    "I have to take a rest this afternoon; it's in my programme for the day.",
    "No, not this evening.",
    "I sincerely hope you'll keep up your good resolutions. But this evening I have to meet some friends for a drink.",
    "I've promised to go. I always keep my word.",
    "It's not a habit with me, you know. It's not the same as with you. With you ... you're … it's not the same thing at all",
    "I'm no drunkard, not me!",
    "Because there's moderation in all things. I'm a moderate person, not like you!",
    "I said that!",
    "Whatever's happening?",
    "Oh, a rhinoceros!",
    "Oh, a rhinoceros!",
    "It's rushing straight ahead, brushing up against the shop windows."
]